Document: dunst
Title: Debian dunst Manual
Author: <insert document author here>
Abstract: This manual describes what dunst is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dunst/dunst.sgml.gz

Format: postscript
Files: /usr/share/doc/dunst/dunst.ps.gz

Format: text
Files: /usr/share/doc/dunst/dunst.text.gz

Format: HTML
Index: /usr/share/doc/dunst/html/index.html
Files: /usr/share/doc/dunst/html/*.html
